#! /bin/sh

#Autostart
pkill -x sxhkd; sxhkd -c ~/.config/sxhkd/sxhkdrc &
numlockx on &
xsetroot -cursor_name left_ptr &
~/.fehbg &
pkill -x dunst; dunst -conf ~/.config/dunst/dunstrc &
~/.config/polybar/launch.sh
killall -q picom; picom -b --config $HOME/.config/picom.conf --experimental-backend

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config external_rules_command "$HOME/.local/bin/bspwmextrules"

#bspc rule -a Google-chrome desktop=1
#bspc rule -a discord desktop=4
#bspc rule -a TelegramDesktop desktop=4 follow=on
