#!/usr/bin/env bash

count=0
disconnected="Disconnected"
wireless_connected="$(nmcli -t -f active,ssid dev wifi | egrep '^так' | cut -d\: -f2)"
ethernet_connected="Ethernet"

ID="$(ip link | awk '/state UP/ {print $2}')"

if (ping -c 1 google.com) &>/dev/null; then
    if [[ $ID == e* ]]; then
        echo "$ethernet_connected" ;
    else
        echo "$wireless_connected" ;
    fi
else
    echo "$disconnected" ;
fi
